[package]
name = "launchdarkly-sdk-common"
version = "0.1.0"
authors = ["Sam Stokes <sstokes@launchdarkly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.15"
log = "0.4.11"
regex = "1.3.9"
serde = { version = "1.0.115", features = ["derive"] }
semver = "0.10.0"
serde_json = "1.0.57"
sha1 = { version = "0.6.0", features = ["std"] }

[dev-dependencies]
maplit = "1.0.1"
spectral = "0.6.0"
